### ISSUE TITLE
Running a .bat script to change the directory does not change the directory

### ISSUE THREAD

**Issue by Beliavsky** [malxau/yori#89] opened 2021-02-16 13:11 UTC
If I have a script foo.bat with contents "cd c:\foo", running that script within yori does not change the directory. In CMD it does.

**Comment by pyproman** [comment] 2021-02-16 19:34
Duplicate of #51
If you want to change directory via scripts in Yori, just rename it to .ys1 so it is executed by Yori, not CMD

**Comment by malxau** [comment] 2021-02-16 19:47
In #51 , I said that fixing this may be possible but hadn't looked into it.  It looks like somebody else described how this can work at https://stackoverflow.com/questions/14018280/how-to-get-a-process-working-dir-on-windows which is almost exactly how Yori is currently getting the environment block from CMD processes, so I should just be able to extend this logic to the current directory as well.  If two people have hit this, it seems likely to keep causing problems for other people too.

**Comment by malxau** [comment] 2021-04-03 21:03
This should be fixed in 1.50, released today.  Please let me know if there are further related issues.

**Closed by malxau** 2021-04-03 21:03 UTC
Labels: fixed in master
