### ISSUE TITLE
mklink command fails silently

### ISSUE THREAD

**Issue by Migod11** [malxau/yori#20] opened 2020-01-23 14:36 UTC
Well, title says it all: mklink /D does nothing ?

**Comment by malxau** [comment] 2020-01-24 03:05
Thanks for the report.  I pushed a fix for it now.  The cause was mis-declaring the CreateSymbolicLink function as returning a 32 bit value instead of an 8 bit value; because return values are in registers, this means that if CreateSymbolicLink set the low 8 bits to zero (indicating failure) but any of the other 24 bits were nonzero, Yori would believe the call had succeeded rather than failed.  Whether this occurs depends on other implementation details inside CreateSymbolicLink.

**Comment by malxau** [comment] 2020-03-21 18:19
I just released 1.21 which I believe fixes this issue.  You can upgrade an existing install with `ypm -u`.  If you find any additional problems, please either reopen this issue or file a new one describing that problem.  Thanks for the report!

**Closed by malxau** 2020-03-21 18:19 UTC
